image: python
stages:          
  - test

test-job-1:   
  stage: test 
  before_script:
    - pip install pytest
    - pip install selenium
  services:
    - selenium/standalone-chrome
  script:
    - pytest test_First.py

test-job-2:   
  stage: test 
  before_script:
    - pip install pytest
    - pip install selenium
  services:
    - selenium/standalone-chrome
  script:
    - pytest test_Second.py
  
